global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: '${GMAIL}'
    from: '${GMAIL}'
    smarthost: 'smtp.gmail.com:587'
    auth_username: '${GMAIL}'
    auth_password: '${GMAIL_PASS}'
    auth_identity: '${GMAIL}'
    send_resolved: true

