global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "/etc/prometheus/node_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  # Prometheus self-auditing
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  # Bare-Metal Server Node Metrics (Hits Host OS directly)
  - job_name: 'node'
    static_configs:
      - targets: ['host.containers.internal:9100']

  # Target Java Applications outside Podman
  - job_name: 'spring-boot-demo-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.containers.internal:8084']

  # Blackbox Active Endpoint Synthetics
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://grafana:3000            # Probes Grafana locally inside the Pod
        - https://ibrahimmoalim.dev        # External Production Target
        - https://api.ibrahimmoalim.dev    # External API Target
        - http://host.containers.internal:8081/api/users   # Internal App Endpoint on Host
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115        # Redirects payload traffic into the Pod's prober engine
